#pragma once
#include <bedrocktc/Version.hpp>
#include <bedrocktc/version/Version.hpp>
#include <bedrocktc/version/VersionData.hpp>
#include <bedrocktc/version/VersionResolver.hpp>
#include <bedrocktc/Core.hpp>
#include <bedrocktc/Api.hpp>
#include <bedrocktc/client/Client.hpp>
#include <bedrocktc/world/World.hpp>
#include <bedrocktc/entity/Entity.hpp>
#include <bedrocktc/events/Events.hpp>
#include <bedrocktc/events/EventBus.hpp>
#include <bedrocktc/render/Render.hpp>
#include <bedrocktc/input/Input.hpp>
#include <bedrocktc/network/Network.hpp>
#include <bedrocktc/memory/Memory.hpp>
#include <bedrocktc/signatures/Signatures.hpp>
#include <bedrocktc/hooks/Hooks.hpp>
#include <bedrocktc/patches/Patch.hpp>
#include <bedrocktc/config/ConfigManager.hpp>
#include <bedrocktc/modules/Module.hpp>
#include <bedrocktc/modules/ModuleRegistry.hpp>
